# Generated by Django 3.2.9 on 2021-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_questionmodel_img_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='img_question',
            field=models.ImageField(blank=True, null=True, upload_to='questions'),
        ),
    ]
