# Generated by Django 3.2.9 on 2021-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quizzlog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzlog',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
