# Generated by Django 3.2.8 on 2021-11-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_questionmodel_img_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzHistroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, null=True)),
                ('user_and_score', models.JSONField(null=True)),
                ('winner', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
