# Generated by Django 3.2.9 on 2021-11-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_questionmodel_img_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exel_file_upload', models.FileField(upload_to='question_exel')),
            ],
        ),
    ]
