# Generated by Django 3.2.8 on 2021-12-01 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_quizzhistroy'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, null=True)),
                ('winner', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizzUserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('quizzlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quizzlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QuizzHistroy',
        ),
        migrations.AddField(
            model_name='quizzlog',
            name='user',
            field=models.ManyToManyField(through='core.QuizzUserScore', to=settings.AUTH_USER_MODEL),
        ),
    ]
