# Generated by Django 3.2.8 on 2021-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
