# Generated by Django 3.2.8 on 2021-12-03 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_userscore_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=20, null=True)),
                ('sub_category', models.CharField(max_length=200, null=True)),
                ('room_code', models.CharField(max_length=20, null=True)),
                ('active_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='QuizzUserScore',
            new_name='UserQuizzScore',
        ),
        migrations.RenameModel(
            old_name='UserScore',
            new_name='UserTotalScore',
        ),
    ]
