# Generated by Django 3.2.8 on 2021-12-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211203_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.AddField(
            model_name='quizzlog',
            name='active_flag',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
