# Generated by Django 3.2.8 on 2021-12-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quizzlog_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzlog',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
