# Generated by Django 3.2.9 on 2021-12-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_quizzlog_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizzscore',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usertotalscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
